version: '3'

services:
  pjdocker: 
    container_name: backend
    # image: node:jessie
    build: ./
    command: npm start
    working_dir: /pjdocker/
    enviroment: 
      SECRET_ENV: THIS_IS_A_SECRET
    ports:
      - "3001:3001"
    volumes:
      - ./:/pjdocker/
    